### ISSUE TITLE
GitExtensions freezes

### ISSUE THREAD

**Issue by jbialobr** [pedropombeiro/gitextensions#1]
I logged in as a guest. After selecting a revision I can click on other revision for about 10 secodns, after that time GitExt freezes for 30-40 seconds. It consumes all CPU.
During the first 10 seconds I can change repository, but GitExt will freeze inspite of it.

![moz-screenshot-8](https://f.cloud.github.com/assets/1003909/265560/d9c43e3e-8db4-11e2-8fbf-df3ed1e3eaa6.jpg)

**Comment by jbialobr** [comment]
![moz-screenshot-9](https://f.cloud.github.com/assets/1003909/265612/83157484-8db6-11e2-87c2-01c4a78caa83.jpg)

**Comment by jbialobr** [comment]
I did some testing and see that it is old IE problem. But still, build report page should be unloaded when build report tab gets removed.

**Comment by pedropombeiro** [comment]
I could call the following, forcing the browser to stop, and clearing it's document. Want to try that?

```
BuildReportWebBrowser.Stop();
BuildReportWebBrowser.Document.Write(string.Empty);
```

**Comment by jbialobr** [comment]
Sure.

**Comment by pedropombeiro** [comment]
Done.
