### ISSUE TITLE
Building on mono

### ISSUE THREAD

**Issue by fraga** [pedropombeiro/gitextensions#12]
hey @pcworld have you ever tried to build this branch?

**Comment by pcworld** [comment]
@fraga I have no experience at all with CI build servers

**Comment by fraga** [comment]
sorry, I wasn't specific @pcworld, I meant - if you could download this branch iand build it using monodevelop/xamarin

**Comment by pcworld** [comment]
> if you could download this branch iand build it using monodevelop/xamarin

Well, I can try to build it, but can't really test if it works as intended.

**Comment by fraga** [comment]
@pcworld don't need to test the plugin for now, this plugin has been disable in mono because webbrowser type is not supported out of the box. We need to test gitextensions usability here since there's a lot of changes (for example full .net 4.0 on the project was implemented here)

**Comment by pcworld** [comment]
Currently failing to find `Nini` and `IConfig`, were they added to some packages.config? If so, will have to reboot into Windows, since nuget doesn't seem to work on this Mono version.

**Comment by pcworld** [comment]
Nevermind, it _is_ included in some packages.config, and I could also download it from http://nini.sourceforge.net/download.php,
and the HttpClient from http://packages.nuget.org/api/v1/package/Microsoft.Net.Http/2.0.20710.0 (see http://stackoverflow.com/a/8744201)

**Comment by fraga** [comment]
@pcworld, is Nuget.sh failing for you?

**Comment by pcworld** [comment]
Yup, nuget doesn't seem to work on older Mono versions.

I have _massive_ problems with rendering on Mono 2.10.8.1 on Ubuntu 12.04, Git Ext is pretty much unusable. But had many problems in that regard with master as well, so can't really tell if this branch makes it even worse.
Will have to test on Windows.
