### ISSUE TITLE
Move build server settings to Settings dialog.

### ISSUE THREAD

**Issue by jbialobr** [pedropombeiro/gitextensions#2]
Also add setting to disable showing build report inspite of existing properly configured .buildsever file.

**Comment by pedropombeiro** [comment]
Is it OK to place this page outside the Plugins node? From what I see, the plugin pages are autogenerated, and only contain text boxes.

**Comment by jbialobr** [comment]
We are about to reorganize settings pages tree, so yes (maybe it will be moved in the future).

**Comment by pedropombeiro** [comment]
Do you know how do I get the Module.GitWorkingDir from inside a SettingsPageBase?

**Comment by jbialobr** [comment]
You cann't. You can change it's base to GitModuleControl or pass GitModule instance to your page directly as in LocalSettingsSettingsPage.

**Comment by pedropombeiro** [comment]
OK. The settings page is there now. Just miss the checkbox to disable integration.

**Comment by jbialobr** [comment]
There should be some validations performed before trying to save config.

System.ArgumentNullException was caught
  Message=Wartość nie może być zerowa.
Nazwa parametru: Value cannot be null
  Source=Nini
  ParamName=Value cannot be null
  StackTrace:
       w Nini.Config.ConfigBase.Set(String key, Object value)
       w GitUI.CommandsDialogs.SettingsDialog.Pages.BuildServerIntegrationSettingsPage.<>c__DisplayClass3.<SaveSettings>b__2(String x) w D:\projekty\gitextensions\GitUI\CommandsDialogs\SettingsDialog\Pages\BuildServerIntegrationSettingsPage.cs:wiersz 70
       w GitCommands.FileInfoExtensions.MakeFileTemporaryWritable(String fileName, Action`1 writableAction) w D:\projekty\gitextensions\GitCommands\FileInfoExtensions.cs:wiersz 18
       w GitUI.CommandsDialogs.SettingsDialog.Pages.BuildServerIntegrationSettingsPage.SaveSettings() w D:\projekty\gitextensions\GitUI\CommandsDialogs\SettingsDialog\Pages\BuildServerIntegrationSettingsPage.cs:wiersz 58
  InnerException:

**Comment by pedropombeiro** [comment]
Added checkbox to enable integration and fix exception with latest commit.
