### ISSUE TITLE
Mono Failed to load plugin System.Net.Http.dll

### ISSUE THREAD

**Issue by fraga** [pedropombeiro/gitextensions#5]
As soon as I start the application, it gives me Failed to load plugin System.Net.Http.dll - could not load type 'System.Net.Http.FormUrlEncodedContent' from assembly 'System.Net.Http' version 2.0. 

We need to target another lib for the job..

**Comment by pedropombeiro** [comment]
Apparently this class is a part of Mono: https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs. Maybe a newer version, or only .NET 4.5?

**Comment by fraga** [comment]
Looks new implementation. What are the impacts if we target 4.5 just to check it out?

**Comment by pedropombeiro** [comment]
On the Windows side, it would be just a matter of removing the respective NuGet package from the project, since HttpClient would come included in .NET 4.5. On the Mono end of things, I couldn't say.

**Comment by fraga** [comment]
same thing, I will try

**Comment by pedropombeiro** [comment]
Thanks!

**Comment by fraga** [comment]
I don't have more problems with this issue, I was able to build and it's working on mono
