### ISSUE TITLE
Mono fails to understand lambda on method GetBuilds

### ISSUE THREAD

**Issue by fraga** [pedropombeiro/gitextensions#6]
Probably mono compiler error, but on the following method:

``` csharp
public IObservable<BuildInfo> GetBuilds(IScheduler scheduler, DateTime? sinceDate = null, bool? running = null)
        {
            if (httpClient == null || httpClient.BaseAddress == null || string.IsNullOrEmpty(ProjectName))
            {
                return Observable.Empty<BuildInfo>(scheduler);
            }

            return Observable.Create<BuildInfo>((observer, cancellationToken) =>
                Task<IDisposable>.Factory.StartNew(
                    () => scheduler.Schedule(() =>
```

I have the following errors:

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(76,76): Error CS1061: Type `System.Threading.Tasks.Task' does not contain a definition for`Result' and no extension method `Result' of type`System.Threading.Tasks.Task' could be found (are you missing a using directive or an assembly reference?) (CS1061) (GitUI)

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(49,49): Error CS0825: The contextual keyword `var' may only appear within a local variable declaration (CS0825) (GitUI)

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(53,53): Error CS0126: An object of a type convertible to `__arglist' is required for the return statement (CS0126) (GitUI)

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(37,37): Error CS1501: No overload for method `Schedule' takes`1' arguments (CS1501) (GitUI)

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(70,70): Error CS1061: Type `System.Net.Http.HttpContent' does not contain a definition for`Headers' and no extension method `Headers' of type`System.Net.Http.HttpContent' could be found (are you missing a using directive or an assembly reference?) (CS1061) (GitUI)

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(50,50): Error CS0029: Cannot implicitly convert type `System.Threading.Tasks.Task<System.IO.Stream>' to`void' (CS0029) (GitUI)

/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(50,50): Error CS1662: Cannot convert `lambda expression' to delegate type`System.Action<System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>>' because some of the return types in the block are not implicitly convertible to the delegate return type (CS1662) (GitUI)

Since it  builds with no problem on MS .NET, that's probably a mono issue.

**Comment by pedropombeiro** [comment]
I refactored that method a bit, to try to see if it helps. If you'd like, you can get the latest and give it a try.

**Comment by fraga** [comment]
Investigating a bit more, It seems mono Didn't implement Result property on type Task, only on TAsk<>

**Comment by fraga** [comment]
Check this out @PombeirP https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Threading.Tasks/Task.cs

**Comment by fraga** [comment]
Mono compiler does not understand that method .ContinueWith has the type Task<string[]> it understands as Task

``` csharp
.ContinueWith(
                        buildIdTask => PerformBuildTasks(buildIdTask, observer, cancellationToken),
                        cancellationToken,
                        TaskContinuationOptions.ExecuteSynchronously,
                        TaskScheduler.Current);
```

On their code I sent you I can see only .ContinueWith(Action<<Task>> and I suppose we should get implementation of .ContinueWith(Action<<Task<<T>>>> right?

Is there a way we could refactor your method so that we get around .ContinueWith for this moment?

**Comment by pedropombeiro** [comment]
I was able to get rid of that .ContinueWith. Please let me know if it improved things.

**Comment by fraga** [comment]
Will try it later today

**Comment by fraga** [comment]
@PombeirP do you have VMWARE?

**Comment by pedropombeiro** [comment]
I could install VMWare Player, but if you mean Workstation, then no, I
don't.

**Comment by fraga** [comment]
Ok. Just because there's a vm that you can download with linux + mono. 

Well, with mono 2.10.9 I have a lot of issues, I am installing newest mono now 3.0.6 (2.12.11) to check how it will build gitext

**Comment by pedropombeiro** [comment]
Can you point me to the VM?

2013/3/20 Rodrigo Fraga notifications@github.com

**Comment by fraga** [comment]
I can't find it. Well at least with mono 3.0.6 I got other issues

Maybe best for you to do is to install Xamarin Studio and mono from here http://www.go-mono.com/mono-downloads/download.html

That's what I've done

**Comment by fraga** [comment]
Things improved @PombeirP but I still have 3 errors I can't really understand, it cannot build!

```
/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(70,70): Error CS1061: Type `System.Net.Http.HttpContent' does not contain a definition for `Headers' and no extension method `Headers' of type `System.Net.Http.HttpContent' could be found (are you missing a using directive or an assembly reference?) (CS1061) (GitUI)
```

```
/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(50,50): Error CS0029: Cannot implicitly convert type `System.Threading.Tasks.Task<System.IO.Stream>' to `void' (CS0029) (GitUI)
```

and

```
/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(50,50): Error CS1662: Cannot convert `lambda expression' to delegate type `System.Action<System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>>' because some of the return types in the block are not implicitly convertible to the delegate return type (CS1662) (GitUI)
```

**Comment by pedropombeiro** [comment]
The latest check-in could address the 3rd (and potentially the 2nd) issue.

**Comment by fraga** [comment]
Great job @PombeirP you killed one issue

I still have

```
/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(41,41): Error CS0584: Internal compiler error: Method not found: 'System.Net.Http.HttpContent.SerializeToStreamAsync'. (CS0584) (GitUI)
```

and

```
/Users/fraga/proj/VS/gitextensions/GitUI/BuildServerIntegration/TeamCityAdapter.cs(49,49): Error CS1061: Type `object' does not contain a definition for `ContentType' and no extension method `ContentType' of type `object' could be found (are you missing a using directive or an assembly reference?) (CS1061) (GitUI)
```

I think we are missing a reference, could it be System.Net.Http.HttpFormatting? I can't see this reference here in mono libs or add it through nuget..

For now, what I could do is disable those functions and the webbrowser

**Comment by pedropombeiro** [comment]
Yeah, it seems Mono support for this type of expressions is still not full-fledged enough. That would be nice if you could disable it in Mono. That would allow us to proceed with Windows, at least.

**Comment by fraga** [comment]
How do you see this though, completeling disabling the tab?

Do you already have a master switch for the build server integration?

**Comment by pedropombeiro** [comment]
Yes, there is a setting in the Settings class for this purpose.

**Comment by fraga** [comment]
Well I think we can close this issue for the moment, I'm able to build it and run.
